"""Canonical NFL team registry. Reuses logic from Answer Keys/canonical_match.py."""

TEAMS: dict[str, dict] = {
    "ARI": {"full_name": "Arizona Cardinals", "aliases": ["ARI", "Arizona", "Cardinals", "Arizona Cardinals"]},
    "ATL": {"full_name": "Atlanta Falcons", "aliases": ["ATL", "Atlanta", "Falcons", "Atlanta Falcons"]},
    "BAL": {"full_name": "Baltimore Ravens", "aliases": ["BAL", "Baltimore", "Ravens", "Baltimore Ravens"]},
    "BUF": {"full_name": "Buffalo Bills", "aliases": ["BUF", "Buffalo", "Bills", "Buffalo Bills"]},
    "CAR": {"full_name": "Carolina Panthers", "aliases": ["CAR", "Carolina", "Panthers", "Carolina Panthers"]},
    "CHI": {"full_name": "Chicago Bears", "aliases": ["CHI", "Chicago", "Bears", "Chicago Bears"]},
    "CIN": {"full_name": "Cincinnati Bengals", "aliases": ["CIN", "Cincinnati", "Bengals", "Cincinnati Bengals"]},
    "CLE": {"full_name": "Cleveland Browns", "aliases": ["CLE", "Cleveland", "Browns", "Cleveland Browns"]},
    "DAL": {"full_name": "Dallas Cowboys", "aliases": ["DAL", "Dallas", "Cowboys", "Dallas Cowboys"]},
    "DEN": {"full_name": "Denver Broncos", "aliases": ["DEN", "Denver", "Broncos", "Denver Broncos"]},
    "DET": {"full_name": "Detroit Lions", "aliases": ["DET", "Detroit", "Lions", "Detroit Lions"]},
    "GB": {"full_name": "Green Bay Packers", "aliases": ["GB", "GNB", "Green Bay", "Packers", "Green Bay Packers"]},
    "HOU": {"full_name": "Houston Texans", "aliases": ["HOU", "Houston", "Texans", "Houston Texans"]},
    "IND": {"full_name": "Indianapolis Colts", "aliases": ["IND", "Indianapolis", "Colts", "Indianapolis Colts"]},
    "JAX": {"full_name": "Jacksonville Jaguars", "aliases": ["JAX", "JAC", "Jacksonville", "Jaguars", "Jacksonville Jaguars"]},
    "KC": {"full_name": "Kansas City Chiefs", "aliases": ["KC", "KAN", "Kansas City", "Chiefs", "Kansas City Chiefs"]},
    "LV": {"full_name": "Las Vegas Raiders", "aliases": ["LV", "LVR", "Las Vegas", "Raiders", "Las Vegas Raiders", "Oakland Raiders"]},
    "LAC": {"full_name": "Los Angeles Chargers", "aliases": ["LAC", "LA Chargers", "Chargers", "Los Angeles Chargers"]},
    "LAR": {"full_name": "Los Angeles Rams", "aliases": ["LAR", "LA Rams", "Rams", "Los Angeles Rams"]},
    "MIA": {"full_name": "Miami Dolphins", "aliases": ["MIA", "Miami", "Dolphins", "Miami Dolphins"]},
    "MIN": {"full_name": "Minnesota Vikings", "aliases": ["MIN", "Minnesota", "Vikings", "Minnesota Vikings"]},
    "NE": {"full_name": "New England Patriots", "aliases": ["NE", "NEP", "New England", "Patriots", "New England Patriots"]},
    "NO": {"full_name": "New Orleans Saints", "aliases": ["NO", "NOR", "New Orleans", "Saints", "New Orleans Saints"]},
    "NYG": {"full_name": "New York Giants", "aliases": ["NYG", "NY Giants", "Giants", "New York Giants"]},
    "NYJ": {"full_name": "New York Jets", "aliases": ["NYJ", "NY Jets", "Jets", "New York Jets"]},
    "PHI": {"full_name": "Philadelphia Eagles", "aliases": ["PHI", "Philadelphia", "Eagles", "Philadelphia Eagles"]},
    "PIT": {"full_name": "Pittsburgh Steelers", "aliases": ["PIT", "Pittsburgh", "Steelers", "Pittsburgh Steelers"]},
    "SF": {"full_name": "San Francisco 49ers", "aliases": ["SF", "SFO", "San Francisco", "49ers", "San Francisco 49ers", "Niners"]},
    "SEA": {"full_name": "Seattle Seahawks", "aliases": ["SEA", "Seattle", "Seahawks", "Seattle Seahawks"]},
    "TB": {"full_name": "Tampa Bay Buccaneers", "aliases": ["TB", "TBB", "Tampa Bay", "Buccaneers", "Bucs", "Tampa Bay Buccaneers"]},
    "TEN": {"full_name": "Tennessee Titans", "aliases": ["TEN", "Tennessee", "Titans", "Tennessee Titans"]},
    "WAS": {"full_name": "Washington Commanders", "aliases": ["WAS", "WSH", "Washington", "Commanders", "Washington Commanders"]},
}
